postgres:
        build: ./Postgres
        hostname: postgres
        expose:
                - 5432
                - 80
        ports:
                - "80:80"
                - "5432:5432"

iotcontrollerreceiver:
        build: ./iot_controller_receiver
        hostname: iotcontrollerreceiver
        expose:
                - 8181
                - 61616
        ports:
                - "10000:8181"
                - "61616:61616"

iotdatacenterreceiver:
        build: ./iot_datacenter_receiver
        hostname: iotdatacenterreceiver
        expose:
                - 8181
                - 61616
        ports:
                - "10003:8181"
        links:
                - postgres

iotdatacenterbpm:
        build: ./iot_datacenter_bpm
        hostname: iotdatacenterbpm
        expose:
                - 8080
                - 9990
        ports:
                - "10004:8080"
                - "10005:9990"

iotcontrollercep:
        build: ./iot_controller_cep
        hostname: iotcontrollercep
        links:
               - iotcontrollerreceiver
               - iotdatacenterreceiver
               - postgres

iotdatacentermonitor:
        build: ./iot_datacenter_monitor
        hostname: iotdatacentermonitor
        links:
               - iotdatacenterreceiver
               - iotdatacenterbpm

iotdatacenterdashboard:
        build: ./iot_datacenter_dashboard
        hostname: iotdatacenterdashboard
        links:
               - postgres
        expose:
                - 8080
                - 9990

        ports:
                - "10006:8080"
                - "10007:9990"
